[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  # Configuración segura del escaneo de secretos
  SECRETS_SCAN_ENABLED = "true"
  # Omitir archivos de documentación y configuración que no son código de producción
  SECRETS_SCAN_OMIT_PATHS = "archive-legacy-files/**,docs/**,*.md,*.MD,package-lock.json,.netlify/**,SUPABASE_CONFIGURATION.md,env.example,build-config.md,netlify-build-config.md"
  # Omitir nombres de variables de ejemplo que no son secretos reales
  SECRETS_SCAN_OMIT_KEYS = "your_supabase_url_here,your_supabase_anon_key_here,your_hcaptcha_site_key_here,example_url,example_key,placeholder_value"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
